### PR TITLE
Solve ATM Queue problem from round F in C

### PR DESCRIPTION
**Pull request by Krish03na**
## Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/CONTRIBUTING.md) file first.

Yes

## Description

Solve ATM Queue problem from round F in C

## Checklist
- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
 
## Related Issues

Fixes Issue #5

### CODE REVIEW

**Comment by Krish03na** [comment]
Please merge this whenever you get time @lostgirljourney 
Please ignore previous commits, and let me know if there is any issue with merging.

**Comment by lostgirljourney** [comment]
there are 4 files, i expect here 2. please check once.

**Comment by Krish03na** [comment]
Please check now @lostgirljourney

**Comment by Krish03na** [comment]
Could you merge this? @lostgirljourney

**Comment by lostgirljourney** [comment]
@Krish03na done 🚀

**Comment by Krish03na** [comment]
Thank you @lostgirljourney 
[:keanu-thanks:](https://gfycat.com/polishedpiercingcusimanse)

**Pull request merged**
