### PR TITLE
added solutions in C++

### PR DESCRIPTION
**Pull request by ayerhs7**
Hey There! I'm adding the solutions in C++

### CODE REVIEW

**Comment by lostgirljourney** [comment]
Please follow the guidelines, you've to follow them otherwise I can't merge your PR.
Close this PR and go to repository, check out the Guideline.md file & PR again.
@ayerhs7

**Comment by lostgirljourney** [comment]
I'll close within 24 hours.

**Comment by ayerhs7** [comment]
okay wait I'm gonna do that

**Comment by lostgirljourney** [comment]
@ayerhs7 I'm closing this. If you wanna work; do it according to the Guidelines.
**#Reminder: Do it asap else unassigning you.**

**Pull request closed without merging**
