### PR TITLE
added solution to stable wall in C

### PR DESCRIPTION
**Pull request by Krish03na**
## Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/CONTRIBUTING.md) file first.

Yes

## Description

Added solution for Round C Stable Wall problem in C language

## Checklist
- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
 
## Related Issues

Fixes Issue #8

### CODE REVIEW

**Comment by Krish03na** [comment]
@lostgirljourney Please check the PR and approve it before the Hacktoberfest deadline tomorrow 🙏

**Comment by lostgirljourney** [comment]
Please check that the image you attaching should seem similar to something like this.

ss

**Comment by Krish03na** [comment]
Pasted wrong screenshot 🤦‍♂️ Please check now

**Review by lostgirljourney — APPROVED** [review]

**Comment by lostgirljourney** [comment]
merged 🚀

**Pull request merged**
