### PR TITLE
Issue Number for which I'm assigned & worked: #7

### PR DESCRIPTION
**Pull request by ayerhs7**
Issue Number for which I'm assigned & worked: #7

### CODE REVIEW

**Comment by lostgirljourney** [comment]
🚀 merging

**Comment by ayerhs7** [comment]
you accepted my pull request. Right? Then why isn't it showing there in my hacktoberFest profile?

**Comment by lostgirljourney** [comment]
> you accepted my pull request. Right? Then why isn't it showing there in my HacktoberFest profile?

Can you share the Screenshot?

**Comment by lostgirljourney** [comment]
Screenshot (83)

@ayerhs7 these are the legends.

**Pull request merged**
